FROM alpine:3.16 as certs
RUN apk --update add ca-certificates

FROM scratch

ARG USER_UID=10001
USER ${USER_UID}

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --chmod=755 prometheus-deepflow-adapter /prometheus-deepflow-adapter
ENTRYPOINT ["/prometheus-deepflow-adapter"]
