FROM debian:buster

RUN echo 'deb http://mirrors.aliyun.com/debian/ buster main non-free contrib \n\
deb http://mirrors.aliyun.com/debian-security buster/updates main \n\
deb http://mirrors.aliyun.com/debian/ buster-updates main non-free contrib \n\
deb http://mirrors.aliyun.com/debian/ buster-backports main non-free contrib \n' \
> /etc/apt/sources.list \
&& apt-get -qq update

RUN apt install -y ca-certificates curl wget
COPY ./ /prometheus-deepflow-adapter
ENTRYPOINT ["/prometheus-deepflow-adapter/prometheus-deepflow-adapter"]
